import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import NextTopLoader from "nextjs-toploader"
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import { auth } from "@clerk/nextjs/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {userId} = auth();

  return (
      <ClerkProvider> 
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader height={2} color="orange" easing="cubic-bezier(.53,.021,0,1)" showSpinner={false}/>
        <ContextProvider> 
        <GlobalStyleProvider > 
      {userId &&  <Sidebar />}
        <div className="w-full ">

        {children}
        </div>
        </GlobalStyleProvider>
        </ContextProvider>
      </body>
    </html>
        </ClerkProvider>
  );
}
